# Generated by Django 3.0.8 on 2020-09-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_category_comment_listing_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='bid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19),
        ),
        migrations.AlterField(
            model_name='listing',
            name='details',
            field=models.TextField(max_length=1000),
        ),
    ]
